### PR TITLE
Added wpa_supplicant.conf headless internet method

### PR DESCRIPTION
**Pull request by swebra**
Added what I argue to be the easiest method to get any headless Pi online. Based on a stackechange post found [here.](https://raspberrypi.stackexchange.com/questions/10251/prepare-sd-card-for-wifi-on-headless-pi)

I have tested this method myself, and am yet to find any conflicts with P4wnP1. It is great as it requires no additional hardware (besides a SD card reader which the user should already have if they are flashing the Raspbian image), is extremely easy, and supports any operating system that can mount the SD card, Windows included.

### CODE REVIEW

**Comment by Swiftb0y** [comment]
Thanks for adding this method (its my method of choice as well).
I'm sorry for responding so late (I somehow must have missed your PR).
I hope you will continue to contribute to the wiki in the future.

**Review by mame82 — COMMENTED** [review]
Shouldn't ssh be written in lower case or is this feature case insensitive

**Comment by Swiftb0y** [comment]
Good question. I've personally always used lowercase but I can't confirm that the uppercase version won't work as well. I hope @imswebra can shed some light onto this.

**Comment by swebra** [comment]
@Swiftb0y Just tested it with a new deploy, and I can confirm it is case insensitive.

**Pull request merged**
